### ISSUE TITLE
Main Page Language List

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationKeyboardWeb#18]
Possibly we need to consider breaking the language list down by country first and then language.

**Comment by bknatterud** [comment]
do we want this to allow users to select either language or country first or just country first?

**Comment by bknatterud** [comment]
sorry I realize that this is just for the main homepage I was thinking the new keyboard selection box. But I guess the question still applies. Do we want to see both breakdowns on the main page?

**Comment by bknatterud** [comment]
Add regions to the top bar of tK website

On the main page put the Regions list first

**Comment by bknatterud** [comment]
only show the 6 or 7 regions in the region list

**Comment by bknatterud** [comment]
I think this is how you want it now. Please review here and let me know tk.unfoldingword.org

**Comment by jag3773** [comment]
That's getting closer.

1. There are two 'Unknown' entries that need fixed.
2. The pop up dialog is not helpful.  The two letter codes need to be replaced by their corresponding names.
3. There is a gap before the last entry in the pop up.

**Comment by bknatterud** [comment]
1. Those are regions that are unknown. Would you like them to be combined into one unknown region? Unless the langnames file is updated they are still unknown.
2. The only names that would be available would be to just repeat the region name. For example the region "DE" is in the Europe region. So do you want it to say "DE-Europe" in the pop up.
3. I was not completely sure where exactly you were seeing this issue?

**Comment by jag3773** [comment]
1. Yes.
2. Do we not have names for the region codes?  BGshould be Bulgaria right?
3. In the pop up dialog.  You may have to make your window narrower to see this.

**Comment by bknatterud** [comment]
I think each of these 3 issues is fixed now.
